// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://attafrzfvlhivqpqtldh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0dGFmcnpmdmxoaXZxcHF0bGRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjkyNjAsImV4cCI6MjA2NzY0NTI2MH0.MvBYpAumnMV--NTHVp7hn4IgKfb86yqR1sSJYzgW5P0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});